services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: solostack
      POSTGRES_PASSWORD: solostack
      POSTGRES_DB: solostack
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
